### ISSUE TITLE
Cannot remove user 

### ISSUE THREAD

**Issue by roheline** [cert-ee/s4a#14]
Deleting user at first does not generate any errors but user is not deleted either.
Trying to delete user second time generates following error:

```
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete | [info] [user.deleteUser] start
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete | [info] [user.deleteUser] test
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete | [info] [user.deleteUser] done
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete | (node:2295) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete |     at createError (/usr/share/s4a-detector/app/server/node_modules/axios/lib/core/createError.js:16:15)
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete |     at settle (/usr/share/s4a-detector/app/server/node_modules/axios/lib/core/settle.js:18:12)
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete |     at IncomingMessage.handleStreamEnd (/usr/share/s4a-detector/app/server/node_modules/axios/lib/adapters/http.js:201:11)
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete |     at emitNone (events.js:111:20)
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete |     at IncomingMessage.emit (events.js:208:7)
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete |     at endReadableNT (_stream_readable.js:1064:12)
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete |     at process._tickCallback (internal/process/next_tick.js:180:9)
Jun 19 13:40:02 hwdetector pm2[2032]: 13:40:02 0|s4a-dete | (node:2295) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)

```

**Comment by tavipoldma** [comment]
can you share the detector versions from web interface?

**Comment by roheline** [comment]
server 0.16.2 client 0.1.64 main 0.1.68

**Comment by tavipoldma** [comment]
fix will be merged with next PR
