### ISSUE TITLE
user passwords that include special characters are not accepted

### ISSUE THREAD

**Issue by roheline** [cert-ee/s4a#24]
```
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | [info] [passport.login] start
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | [info] [passport.login] martin
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | [info] [passport.login] martin auth ok
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | [info] [user.updatePassword] start
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | [info] [user.updatePassword] test
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | [info] [user.updatePassword] shelljs result  127
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | /usr/share/s4a-detector/app/server/common/models/user.js:139
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |           if (exit_code != 0) throw new Error(stderr);
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |                               ^
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | Error: Updating password for user test
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | /bin/sh: 1: cannot open 4y: No such file
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | /bin/sh: 1: eq: not found
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |     at /usr/share/s4a-detector/app/server/common/models/user.js:139:37
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |     at /usr/share/s4a-detector/app/server/node_modules/shelljs/src/exec.js:204:9
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |     at ChildProcess.exithandler (child_process.js:282:5)
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |     at emitTwo (events.js:126:13)
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |     at ChildProcess.emit (events.js:214:7)
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |     at maybeClose (internal/child_process.js:925:16)
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |     at Socket.stream.socket.on (internal/child_process.js:346:11)
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |     at emitOne (events.js:116:13)
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |     at Socket.emit (events.js:211:7)
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  |     at Pipe._handle.close [as _onclose] (net.js:557:12)
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | error Command failed with exit code 1.
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 0|s4a-detector-api-server  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Sep 25 15:18:53 detector pm2[2436]: [2018-09-25T15:18:53.883Z] PM2 log: App [s4a-detector-api-server] with id [0] and pid [24885], exited with code [1] via signal [SIGINT]
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 PM2                        | App [s4a-detector-api-server] with id [0] and pid [24885], exited with code [1] via signal [SIGINT]
Sep 25 15:18:53 detector pm2[2436]: [2018-09-25T15:18:53.884Z] PM2 log: Starting execution sequence in -fork mode- for app name:s4a-detector-api-server id:0
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 PM2                        | Starting execution sequence in -fork mode- for app name:s4a-detector-api-server id:0
Sep 25 15:18:53 detector pm2[2436]: [2018-09-25T15:18:53.892Z] PM2 log: App name:s4a-detector-api-server id:0 online
Sep 25 15:18:53 detector pm2[2436]: 15:18:53 PM2                        | App name:s4a-detector-api-server id:0 online
```

**Comment by voldemarpanso** [comment]
This is fixed in upsteam version, will be PR-d with the rest of the updates

**Comment by tavipoldma** [comment]
included in PR:
https://github.com/cert-ee/s4a-central/pull/3
https://github.com/cert-ee/s4a-detector/pull/5

**Comment by tavipoldma** [comment]
closing
